name: Tests

on:
  pull_request:
    paths:
      - '**.py'
      - '**.ipynb'


jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: "3.12"]
        os: [ubuntu-latest]
      fail-fast: true
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba Python ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=${{ matrix.python-version }} --file requirements-dev.txt --channel conda-forge

    - name: Install glidertest
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Full Tests
      run: |
        python -m pytest tests/
